name: Deploy to Portainer

on:
  push:
    branches:
      - master
      - main

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Portainer Webhook
        run: curl -X POST https://portainer.julespvx.fr/api/stacks/webhooks/055f7d7f-4b4a-465d-b5c4-faafaa5e00e9