name: Deploy to Portainer

on:
  push:
    branches:
      - master
      - main

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Portainer Webhook
        run: curl -X POST https://portainer.julespvx.fr/api/stacks/webhooks/11e4d753-e42c-43b5-8fb1-9bbd8cb1ca73